Parser
suedadam/42sh pull request #12
Opened 2018-04-05 02:44 UTC by sjatkins12

2018-04-05 03:58 UTC, suedadam requested changes
Please fix the last two things and then you should be good! I'll deal with the rest. Please also point out which files are needed to be merged as I'll be merging based off of specific files instead of the whole branch :)

2018-04-05 03:58 UTC, suedadam commented on input_parser/quoting.c
> +int				handle_embedded_quotes(uint8_t *quoted,
I'll leave this up to you, but I'd suggest to make this function a distributor function to call other functions depending on the `if/elseif` statements. That way it norms.

2018-04-05 03:58 UTC, suedadam commented on input_parser/parser.c
> +		if (!(ret = is_semi(par, *input_str)) ||
This is too long for the function (exceeds norm) - There's 2 real ways you can fix it at this point. I'll let you pick your poison.

- Dispatch table
- Inline function to call each and return the result

2018-04-10 02:22 UTC, tle-huu commented
Norm issues remaining

2018-04-10 23:39 UTC, suedadam approved these changes

2018-04-11 05:37 UTC, merged